# buildspec.yml — AWS CodeBuild instructions
# Version of the buildspec format
version: 0.2

# Environment variables available to all phases
env:
  variables:
    AWS_REGION: eu-west-1
    AWS_ACCOUNT_ID: "339493409635"
    # Ensure no trailing spaces in variable values unless intentional
    ECR_REPO: gr/noshow # Existing ECR repository name
    ECS_CLUSTER: car-repair-cluster # Target ECS cluster
    ECS_SERVICE: car-repair-api-task-service # Target ECS service

# Build phases
phases:
  # Commands to run before the build starts
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      # Authenticate Docker with ECR
      - aws ecr get-login-password --region $AWS_REGION | \
        docker login --username AWS --password-stdin \
        $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      # Get the short commit hash for image tagging
      - COMMIT_HASH=${CODEBUILD_RESOLVED_SOURCE_VERSION:0:7}
      - IMAGE_TAG=$COMMIT_HASH
      - echo "Image tag set to $IMAGE_TAG"

  # Commands to run during the build phase
  build:
    commands:
      - echo "Building Docker image..."
      # Build the Docker image
      - docker build -t $ECR_REPO:$IMAGE_TAG .
      # Tag the image for ECR
      - docker tag $ECR_REPO:$IMAGE_TAG \
        $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG
      - echo "Pushing image to ECR..."
      # Push the image to ECR
      - docker push \
        $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG

  # Commands to run after the build is complete
  post_build:
    commands:
      - echo "Generating imagedefinitions.json for ECS deploy..."
      # Create the imagedefinitions.json file using a heredoc.
      # The '|' indicates a literal block scalar, preserving newlines.
      # The content of this block starts on the next line, indented further.
      - |
        cat > imagedefinitions.json <<EOF
        [
          {
            "name": "car-repair-api-container",
            "imageUri": "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO}:${IMAGE_TAG}"
          }
        ]
EOF 
        # The 'EOF' delimiter for cat must be at the beginning of the line, with no leading/trailing spaces.

# Artifacts to be produced by the build
artifacts:
  files:
    # List of files to include in the build artifacts
    - imagedefinitions.json

