version: 0.2

env:
  variables:
    AWS_REGION: eu-west-1
    AWS_ACCOUNT_ID: "339493409635"
    ECR_REPO: gr/noshow
    ECS_CLUSTER: car-repair-cluster
    ECS_SERVICE: car-repair-api-task-service

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c1-7)
      - IMAGE_TAG=$COMMIT_HASH
      - echo Image tag is $IMAGE_TAG
  build:
    commands:
      - echo Building Docker image...
      - docker build -t ${ECR_REPO}:${IMAGE_TAG} .
      - docker tag  ${ECR_REPO}:${IMAGE_TAG} ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO}:${IMAGE_TAG}
      - echo Pushing image to ECR...
      - docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO}:${IMAGE_TAG}
  post_build:
    commands:
      - echo Writing imagedefinitions.json...
      - echo "[{\"name\":\"car-repair-api-container\",\"imageUri\":\"${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO}:${IMAGE_TAG}\"}]" > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json


